server:
  port: 9999
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/electricity_mall_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      db2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/electricity_mall_2?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      names: db1,db2
    props:
      sql:
        show: true
    sharding:
      tables:
        order:
          actual-data-nodes: db$->{1..2}.order_$->{1..2}
          #分库
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: db$->{user_id % 2+1}
          #分表
          table-strategy:
            inline:
              sharding-column: order_number
              algorithm-expression: order_$->{order_number % 2+1}
          key-generator:
            type: SNOWFLAKE
            column: id
